
name: automerge
on:
  pull_request:
    types: ['closed']

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Automerge
      run: |
        branch_name=$(gh pr view  $PR --jq=.headRefName --json=headRefName)
        echo $branch_name
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.number }}
        
        
    - uses: actions/checkout@v2
      with:
        ref-path: preview
    - run: | 
        branch_current=$(gh pr view  $PR --jq=.headRefName --json=headRefName)
        echo $branch_current
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.number }}
