
name: automerge
on:
  pull_request:
    types: ['closed']

jobs:
  capture_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automerge
        run: |
          branch_name=$(gh pr view  $PR --jq=.headRefName --json=headRefName)
          echo $branch_name > name_of_branch.txt
          
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PR: ${{ github.event.number }}
         
      - name: Capture branch name
        uses: actions/upload-artifact@v1
        with: 
         name: branch
         path: name_of_branch.txt
      
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PR: ${{ github.event.number }}

  checking_merge:
    name: checking_merge
    needs: capture_merge
    runs-on: ubuntu-latest
    steps:
      - name: Export Branch Name
        uses: actions/download-artifact@v1
        with:
          name: branch
      - uses: actions/checkout@v2
        with:
          ref: preview 
      - run: | 
          branch_current=$(git rev-parse --abbrev-ref HEAD)
          echo $branch_current
          git pull 
          echo $branch_current
          echo "------------"
          branch_name=`cat branch/name_of_branch.txt`
          echo $branch_name
          git merge origin/develop
          echo "------------"
          git push
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.number }}
        
        
