name: testgithubevent
on:
  pull_request:
    branches: 
      - preview
    types: ['closed']

jobs:
  capture_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automerge
        run: |
          branch_name=$(gh pr view  $PR --jq=.headRefName --json=headRefName)
          echo $branch_name > name_of_branch.txt
          
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PR: ${{ github.event.number }}
